pipeline{
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/PabloRozas/Tingeso_P1']])
                dir('frontend'){
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }
        stage('Build and Push Docker Image'){
            steps{
                dir('frontend'){
                    bat 'docker build -t pablomacuadarozas/frontend:latest .'
                    bat 'docker push pablomacuadarozas/frontend:latest'
                }
            }
        }
    }
}