pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: "*/master"]], extensions: [], userRemoteConfigs: [[url: "https://github.com/PabloRozas/Tingeso_P1"]])
                dir("tingeso-react"){
                    bat "npm install"
                    bat "npm cache clean --force"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("tingeso-react"){
                    script{
                        withDockerRegistry(credentialsId: "docker-credentials"){
                            bat "docker build -t pablomacuadarozas/frontend:latest ."
                            bat "docker push pablomacuadarozas/frontend:latest"
                        }
                    }
                }
            }
        }
    }
}