version: '3.1'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: bdtingeso
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: adminpassword
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bdtingeso
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=adminpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend
    links:
      - db
    volumes:
      .:/usr/src/app
networks:
  backend:
  frontend:
volumes:
  db_data:

 